Mersenne Prime Number
sachin235/HacktoberFest101 pull request #225
Opened 2022-10-25 17:41 UTC by KB786

Code to print the Mersenne Prime numbers up to the range you set with just an input and a click

2022-10-28 17:11 UTC, sachin235 requested changes

2022-10-28 17:11 UTC, sachin235 commented on mersenneprime.java
> +
Please briefly describe what is Mersenne's Prime number.

2022-10-28 17:12 UTC, sachin235 commented on mersenneprime.java
> +
Also, it would be great if you could add a sample input and output as comments to make it more clear.

2022-10-28 17:12 UTC, sachin235 commented
@KB786 move the file to the Mathematics folder in Java.

2022-10-30 16:56 UTC, merged

2022-10-31 10:10 UTC, KB786 commented
Is my PR merged ?

On Sun, Oct 30, 2022 at 10:27 PM sachin235 ***@***.***> wrote:

> Merged #225 <https://github.com/sachin235/HacktoberFest101/pull/225> into
> master.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/sachin235/HacktoberFest101/pull/225#event-7699412607>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3IUIFKDCSD7WC76W6TJD6DWF2SGLANCNFSM6AAAAAAROGNVDI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>